In [33]:
import numpy as np
import pandas as pd

# Bases : création d'une datafame et extraction de données

* Définir ou créer une dataframe 
* Afficher en tableau
* Renvoyer des colonnes
* Extraire des données
* Méthode .iterrows()
* Sélectionner des données avec conditions
* Ajouter des données
* Récupérer la liste sans doublons de lignes
* Ajouter un attribut (une colonne)
* Obtenir les valeurs distinctes d'une colonne
* Importer un fichier csv (comma separated values) dans une dataframe

In [34]:
fam_pandas = [[100,5,20,80], [50,2.5,10,40],[110,6,22,80]]
noms_pandas = ['maman', 'bébé', 'papa']
mesu_pandas = ['pattes', 'poils', 'queue', 'ventre']

In [35]:
# Définir ou créer une dataframe

fam_pan_np = np.array(fam_pandas)
fam_pan_df = pd.DataFrame(fam_pan_np, index = noms_pandas, columns = mesu_pandas)

print(fam_pan_np)

# Afficher en tableau

fam_pan_df
fam_pan_df.head(3) # pratique quand le tableau est trop grand...

[[100.    5.   20.   80. ]
 [ 50.    2.5  10.   40. ]
 [110.    6.   22.   80. ]]


pattes  poils  queue  ventre
maman   100.0    5.0   20.0    80.0
bébé     50.0    2.5   10.0    40.0
papa    110.0    6.0   22.0    80.0

In [36]:
# Renvoyer des colonnes

print(fam_pan_df["ventre"]) # objet de type 'pandas.Series'
print(fam_pan_df.pattes)
print(fam_pan_df["queue"].values) # vecteur correspondant aux valeurs seul
print(fam_pan_df.poils.values) # vecteur correspondant aux valeurs seul

maman    80.0
bébé     40.0
papa     80.0
Name: ventre, dtype: float64
maman    100.0
bébé      50.0
papa     110.0
Name: pattes, dtype: float64
[20. 10. 22.]
[5.  2.5 6. ]


In [37]:
# Extraire des données

print(fam_pan_df.iloc[2]) # Avec iloc(), indexation positionnelle
print(fam_pan_df.loc["papa"]) # Avec loc(), indexation par label

pattes    110.0
poils       6.0
queue      22.0
ventre     80.0
Name: papa, dtype: float64
pattes    110.0
poils       6.0
queue      22.0
ventre     80.0
Name: papa, dtype: float64


In [38]:
# méthode .iterrows()
# renvoie le contenu de chaque ligne sous forme d'un tuple (< nom_ligne >, < données >)

for nom_ligne, données_ligne in fam_pan_df.iterrows(): # .iterrows renvoie une liste de tuples (nom ligne, données)
    print("Voici le panda %s :\n" %nom_ligne + str(données_ligne) + "\n--------------------")

Voici le panda maman :
pattes    100.0
poils       5.0
queue      20.0
ventre     80.0
Name: maman, dtype: float64
--------------------
Voici le panda bébé :
pattes    50.0
poils      2.5
queue     10.0
ventre    40.0
Name: bébé, dtype: float64
--------------------
Voici le panda papa :
pattes    110.0
poils       6.0
queue      22.0
ventre     80.0
Name: papa, dtype: float64
--------------------


In [39]:
# Sélectionner des données avec conditions

masque = fam_pan_df["ventre"] == 80 # renvoie un tableau de booléens pour chaque panda (ventre de 80 cm ?)
print(masque)
pan_v80 = fam_pan_df[masque] # utilisation d'un masque booléen pour filtrer des données
pan_vnon80 = fam_pan_df[~masque]
print("\n Les pandas à ventre de 80 cm sont :") # ou "famille_panda_df[famille_panda_df["ventre"] == 80]"
print(pan_v80.index)
print("\n Les pandas à ventre autre que 80 cm sont :")
print(pan_vnon80.index)

maman     True
bébé     False
papa      True
Name: ventre, dtype: bool

 Les pandas à ventre de 80 cm sont :
Index(['maman', 'papa'], dtype='object')

 Les pandas à ventre autre que 80 cm sont :
Index(['bébé'], dtype='object')


In [40]:
# Ajouter des données

autres_pan = pd.DataFrame([[105,4,19,80],[100,5,20,80]],columns = fam_pan_df.columns)     
# deux nouveaux pandas
                                 # même colonnes que famille_panda_df
all_pan = fam_pan_df.append(autres_pan)
print(all_pan)

       pattes  poils  queue  ventre
maman   100.0    5.0   20.0    80.0
bébé     50.0    2.5   10.0    40.0
papa    110.0    6.0   22.0    80.0
0       105.0    4.0   19.0    80.0
1       100.0    5.0   20.0    80.0


In [41]:
# Récupérer la liste sans doublons de lignes

pan_uni = all_pan.drop_duplicates() # garde le premier de chaque doublon
print(pan_uni)

       pattes  poils  queue  ventre
maman   100.0    5.0   20.0    80.0
bébé     50.0    2.5   10.0    40.0
papa    110.0    6.0   22.0    80.0
0       105.0    4.0   19.0    80.0


In [42]:
# Divers

# accéder aux noms des colonnes
print(fam_pan_df.columns) 

# ajouter un attribut (une colonne)
fam_pan_df["sexe"] = ["f", "f", "m"]  # la maman et le bébé sont des femelles, le papa est un mâle

print(fam_pan_df)
print(len(fam_pan_df)) # obtenir le nombre de lignes
print(all_pan.ventre.unique()) # obtenir les valeurs distinctes d'une colonne

Index(['pattes', 'poils', 'queue', 'ventre'], dtype='object')
       pattes  poils  queue  ventre sexe
maman   100.0    5.0   20.0    80.0    f
bébé     50.0    2.5   10.0    40.0    f
papa    110.0    6.0   22.0    80.0    m
3
[80. 40.]


In [45]:
# importer un fichier csv (comma separated values) dans une dataframe
import os
print(os.getcwd()) # pour connaître le chemin du répertoire courant
data = pd.read_csv("hubble_data.csv", sep=",") # si non dans le rep courant :"/home/user1/Bureau/data.csv"

C:\Users\Maryse\Desktop\EN COURS\OPENCLASSROOMS\05-Librairies Python Data Science\GIT-Jupyter


In [48]:
data # des indexs ont été rajoutés, les titres de colonnes ont été détectés
data.head(3)

distance  recession_velocity
0     0.032                 170
1     0.034                 290
2     0.214                -130

In [49]:
print(str(data.columns[0]) + "---" + str(data.columns[1]))
print(data.index)
print(np.array([data["distance"]],np.newaxis)) # change la colonne en ligne

distance---recession_velocity
RangeIndex(start=0, stop=24, step=1)
[[0.032 0.034 0.214 0.263 0.275 0.275 0.45  0.5   0.5   0.63  0.8   0.9
  0.9   0.9   0.9   1.    1.1   1.1   1.4   1.7   2.    2.    2.    2.   ]]


# Manipulation avancée : exemple sur les données du titanic


In [51]:
import numpy as np
import pandas as pd
import seaborn as sns
titanic = sns.load_dataset('titanic')

### Affichage partiel

In [101]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [102]:
titanic.tail()

survived  pclass     sex   age  sibsp  parch   fare embarked   class  \
886         0       2    male  27.0      0      0  13.00        S  Second   
887         1       1  female  19.0      0      0  30.00        S   First   
888         0       3  female   NaN      1      2  23.45        S   Third   
889         1       1    male  26.0      0      0  30.00        C   First   
890         0       3    male  32.0      0      0   7.75        Q   Third   

       who  adult_male deck  embark_town alive  alone  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True

In [103]:
titanic.describe(include="all")

survived      pclass   sex         age       sibsp       parch  \
count   891.000000  891.000000   891  714.000000  891.000000  891.000000   
unique         NaN         NaN     2         NaN         NaN         NaN   
top            NaN         NaN  male         NaN         NaN         NaN   
freq           NaN         NaN   577         NaN         NaN         NaN   
mean      0.383838    2.308642   NaN   29.699118    0.523008    0.381594   
std       0.486592    0.836071   NaN   14.526497    1.102743    0.806057   
min       0.000000    1.000000   NaN    0.420000    0.000000    0.000000   
25%       0.000000    2.000000   NaN   20.125000    0.000000    0.000000   
50%       0.000000    3.000000   NaN   28.000000    0.000000    0.000000   
75%       1.000000    3.000000   NaN   38.000000    1.000000    0.000000   
max       1.000000    3.000000   NaN   80.000000    8.000000    6.000000   

              fare embarked  class  who adult_male deck  embark_town alive  \
count   891.000000      889    891  891        891  203          889   891   
unique         NaN        3      3    3          2    7            3     2   
top            NaN        S  Third  man       True    C  Southampton    no   
freq           NaN      644    491  537        537   59          644   549   
mean     32.204208      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
std      49.693429      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
min       0.000000      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
25%       7.910400      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
50%      14.454200      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
75%      31.000000      NaN    NaN  NaN        NaN  NaN          NaN   NaN   
max     512.329200      NaN    NaN  NaN        NaN  NaN          NaN   NaN   

       alone  
count    891  
unique     2  
top     True  
freq     537  
mean     NaN  
std      NaN  
min      NaN  
25%      NaN  
50%      NaN  
75%      NaN  
max      NaN

### Sélections diverses et élimitation

Pour enlever les doublons dans un échantillon sou sous-tableau quelconque :

In [104]:
titanic.age.unique() # affiche la liste des âges en enlevant tous les doublons

array([22.  , 38.  , 26.  , 35.  ,   nan, 54.  ,  2.  , 27.  , 14.  ,
        4.  , 58.  , 20.  , 39.  , 55.  , 31.  , 34.  , 15.  , 28.  ,
        8.  , 19.  , 40.  , 66.  , 42.  , 21.  , 18.  ,  3.  ,  7.  ,
       49.  , 29.  , 65.  , 28.5 ,  5.  , 11.  , 45.  , 17.  , 32.  ,
       16.  , 25.  ,  0.83, 30.  , 33.  , 23.  , 24.  , 46.  , 59.  ,
       71.  , 37.  , 47.  , 14.5 , 70.5 , 32.5 , 12.  ,  9.  , 36.5 ,
       51.  , 55.5 , 40.5 , 44.  ,  1.  , 61.  , 56.  , 50.  , 36.  ,
       45.5 , 20.5 , 62.  , 41.  , 52.  , 63.  , 23.5 ,  0.92, 43.  ,
       60.  , 10.  , 64.  , 13.  , 48.  ,  0.75, 53.  , 57.  , 80.  ,
       70.  , 24.5 ,  6.  ,  0.67, 30.5 ,  0.42, 34.5 , 74.  ])

Et pour supprimer des données (lignes ou colonnes) :

Remarque : les index ne sont pas modifiés !!!

In [97]:
# Supprimer une ligne
titanic.drop(0, inplace = False).head(3) # ne modifie pas la dataframe d'origine
#titanic.drop(0, inplace = True) # modifie la dataframe d'origine

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   

     who  adult_male deck  embark_town alive  alone  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False

In [98]:
#Supprimer une colonne
titanic.drop(columns=["age"], inplace = False).head(3) # ne modifie pas la dataframe d'origine
#titanic.drop(columns=["age"], inplace = True) # modifie la dataframe d'origine

survived  pclass     sex  sibsp  parch     fare embarked  class    who  \
0         0       3    male      1      0   7.2500        S  Third    man   
1         1       1  female      1      0  71.2833        C  First  woman   
2         1       3  female      0      0   7.9250        S  Third  woman   

   adult_male deck  embark_town alive  alone  
0        True  NaN  Southampton    no  False  
1       False    C    Cherbourg   yes  False  
2       False  NaN  Southampton   yes   True

### Au sujet des valeurs non rensignées (NaN) :

Remarquez que l'un d'entre eux n'est pas renseigné :

In [67]:
print("Les âges des dix premiers passagers :")
print(np.array(titanic.age.head(10)))

Les âges des dix premiers passagers :
[22. 38. 26. 35. 35. nan 54.  2. 27. 14.]


Pour que l'âge non renseigné soit replacé par 0 :

In [66]:
print("Les âges des dix premiers passagers :")
print(np.array(titanic.fillna(value={"age": 0}).age.head(10)))

Les âges des dix premiers passagers :
[22. 38. 26. 35. 35.  0. 54.  2. 27. 14.]


Pour que l'âge non renseigné soit remplacé par la valeur précédente :

In [68]:
print("Les âges des dix premiers passagers :")
print(np.array(titanic.fillna(value={"age": 0}).age.head(10)))

Les âges des dix premiers passagers :
[22. 38. 26. 35. 35.  0. 54.  2. 27. 14.]


Pour que les données (lignes) qui comportent au moins 1 NaN soient carrément éliminées :

In [74]:
print("Les âges des dix premiers passagers (seulement les lignes sans aucun NaN):")
print(np.array(titanic.dropna().age.head(10)))

Les âges des dix premiers passagers (seulement les lignes sans aucun NaN):
[38. 35. 54.  4. 58. 34. 28. 19. 49. 65.]


Remarque : on peut aussi appliquer cela aux colonnes :

In [84]:
print("Voici les titres des colonnes dont aucune ligne n'a de NaN :")
print(np.array(titanic.dropna(axis = "columns").columns))
nbe_ss_NaN = len(np.array(titanic.dropna(axis = "columns").columns))
nbe_tot = len(np.array(titanic.columns))
print("-> Seulement {} titres sur {} n'ont aucun 'NaN'.".format(nbe_ss_NaN,nbe_tot))

Voici les titres des colonnes dont aucune ligne n'a de NaN :
['survived' 'pclass' 'sex' 'sibsp' 'parch' 'fare' 'class' 'who'
 'adult_male' 'alive' 'alone']
-> Seulement 11 titres sur 15 n'ont aucun 'NaN'.


### Renommer les colonnes et les index :

Voici comment renommer une colomne simplement :

In [89]:
titanic.rename(columns={"sex":"sexe"}).head(3)

survived  pclass    sexe   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True

Et voici comment changer les index :

In [95]:
f = lambda x: x+1
titanic.rename(index=f).head(3)

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
1         0       3    male  22.0      1      0   7.2500        S  Third   
2         1       1  female  38.0      1      0  71.2833        C  First   
3         1       3  female  26.0      0      0   7.9250        S  Third   

     who  adult_male deck  embark_town alive  alone  
1    man        True  NaN  Southampton    no  False  
2  woman       False    C    Cherbourg   yes  False  
3  woman       False  NaN  Southampton   yes   True

### Tableaux croisés dynamiques

on utilise la méthode .pivot_table de la manière suivante :
(<colonne de la valeur à moyenner>, index='nom_index', columns='nom_column')

In [ ]:
titanic.pivot_table('survived', index='sex', columns='class')